<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!-- 
  File   : voms.xml 
  Author : Piter T. de Boer 
  Info   : 
  
       Additional VOMS servers information. 
       This file will also be scanned in addition to possible other voms.xml files. 
           
       Current search order for VO information is (first matched, first used):  
        - User Configuration : $HOME/.globus/vomsdir/voms.xml
        - Installation       : $VLET_INSTALL/etc/voms.xml 
        - GLobus (host)      : /etc/grid-security/vomsdir/voms.xml           

       The VOMS XML records in this file are generated from voms.inf
-->

<!DOCTYPE voms[
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT admin (#PCDATA)>
  <!ELEMENT port (#PCDATA)>
  <!ELEMENT cert (#PCDATA)>
  <!ELEMENT dn (#PCDATA)>
  <!ELEMENT server (name,port,cert,dn)>
  <!ELEMENT vo (name,admin,server*)>
  <!ELEMENT voms (vo*)>
]>

<!-- generated VOMS.xml from voms.inf -->
<voms>
 
  <vo>
    <name>alice</name>
    <admin>https://lcg-voms.cern.ch:8443/voms/alice/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>lcg-voms.cern.ch</name>
       <port>15000</port>
       <cert>lcg-voms.cern.ch.pem</cert>
       <dn>/DC=ch/DC=cern/OU=computers/CN=lcg-voms.cern.ch</dn>
    </server>
  </vo>
 
  <vo>
    <name>alice</name>
    <admin>https://voms.cern.ch:8443/voms/alice/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.cern.ch</name>
       <port>15000</port>
       <cert>voms.cern.ch.pem</cert>
       <dn>/DC=ch/DC=cern/OU=computers/CN=voms.cern.ch</dn>
    </server>
  </vo>
 
  <vo>
    <name>appsportal.nl</name>
    <admin>https://voms.grid.sara.nl:8443/voms/appsportal.nl/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.grid.sara.nl</name>
       <port>30026</port>
       <cert>voms.grid.sara.nl.pem</cert>
       <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
    </server>
  </vo>
 
  <vo>
    <name>atlas</name>
    <admin>https://lcg-voms.cern.ch:8443/voms/atlas/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>lcg-voms.cern.ch</name>
       <port>15001</port>
       <cert>lcg-voms.cern.ch.pem</cert>
       <dn>/DC=ch/DC=cern/OU=computers/CN=lcg-voms.cern.ch</dn>
    </server>
  </vo>
 
  <vo>
    <name>atlas</name>
    <admin>https://voms.cern.ch:8443/voms/atlas/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.cern.ch</name>
       <port>15001</port>
       <cert>voms.cern.ch.pem</cert>
       <dn>/DC=ch/DC=cern/OU=computers/CN=voms.cern.ch</dn>
    </server>
  </vo>
 
  <vo>
    <name>atlas</name>
    <admin>https://vo.racf.bnl.gov:8443/voms/atlas/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>vo.racf.bnl.gov</name>
       <port>15003</port>
       <cert>vo.racf.bnl.gov.pem</cert>
       <dn>/DC=org/DC=doegrids/OU=Services/CN=vo.racf.bnl.gov</dn>
    </server>
  </vo>
 
  <vo>
    <name>bbmri.nl</name>
    <admin>https://voms.grid.sara.nl:8443/voms/bbmri.nl/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.grid.sara.nl</name>
       <port>30011</port>
       <cert>voms.grid.sara.nl.pem</cert>
       <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
    </server>
  </vo>
 
  <vo>
    <name>beapps</name>
    <admin>https://voms01.begrid.be:8443/voms/beapps/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms01.begrid.be</name>
       <port>18004</port>
       <cert>voms01.begrid.be.pem</cert>
       <dn>/C=BE/O=BEGRID/OU=BEgrid/OU=BELNET/CN=voms01.begrid.be</dn>
    </server>
  </vo>
 
  <vo>
    <name>beapps</name>
    <admin>https://voms02.begrid.be:8443/voms/beapps/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms02.begrid.be</name>
       <port>18004</port>
       <cert>voms02.begrid.be.pem</cert>
       <dn>/C=BE/O=BEGRID/OU=BEgrid/OU=BELNET/CN=voms02.begrid.be</dn>
    </server>
  </vo>
 
  <vo>
    <name>beapps</name>
    <admin>https://voms.begrid.be:8443/voms/beapps/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.begrid.be</name>
       <port>18004</port>
       <cert>voms.begrid.be.pem</cert>
       <dn>/C=BE/O=BEGRID/OU=BEgrid/OU=BELNET/CN=voms.begrid.be</dn>
    </server>
  </vo>
 
  <vo>
    <name>biomed</name>
    <admin>https://cclcgvomsli01.in2p3.fr:8443/voms/biomed/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>cclcgvomsli01.in2p3.fr</name>
       <port>15000</port>
       <cert>cclcgvomsli01.in2p3.fr.pem</cert>
       <dn>/O=GRID-FR/C=FR/O=CNRS/OU=CC-IN2P3/CN=cclcgvomsli01.in2p3.fr</dn>
    </server>
  </vo>
 
  <vo>
    <name>compchem</name>
    <admin>https://voms.cnaf.infn.it:8443/voms/compchem/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.cnaf.infn.it</name>
       <port>15003</port>
       <cert>voms.cnaf.infn.it.pem</cert>
       <dn>/C=IT/O=INFN/OU=Host/L=CNAF/CN=voms.cnaf.infn.it</dn>
    </server>
  </vo>
 
  <vo>
    <name>dans</name>
    <admin>https://voms.grid.sara.nl:8443/voms/dans/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.grid.sara.nl</name>
       <port>30016</port>
       <cert>voms.grid.sara.nl.pem</cert>
       <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
    </server>
  </vo>
 
  <vo>
    <name>dteam</name>
    <admin>https://voms2.hellasgrid.gr:8443/voms/dteam/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms2.hellasgrid.gr</name>
       <port>15004</port>
       <cert>voms2.hellasgrid.gr.pem</cert>
       <dn>/C=GR/O=HellasGrid/OU=hellasgrid.gr/CN=voms2.hellasgrid.gr</dn>
    </server>
  </vo>
 
  <vo>
    <name>dteam</name>
    <admin>https://voms.hellasgrid.gr:8443/voms/dteam/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.hellasgrid.gr</name>
       <port>15004</port>
       <cert>voms.hellasgrid.gr.pem</cert>
       <dn>/C=GR/O=HellasGrid/OU=hellasgrid.gr/CN=voms.hellasgrid.gr</dn>
    </server>
  </vo>
 
  <vo>
    <name>dzero</name>
    <admin>https://voms.fnal.gov:8443/voms/dzero/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.fnal.gov</name>
       <port>15002</port>
       <cert>voms.fnal.gov.pem</cert>
       <dn>/DC=org/DC=doegrids/OU=Services/CN=http/voms.fnal.gov</dn>
    </server>
  </vo>
 
  <vo>
    <name>emutd</name>
    <admin>https://voms.grid.sara.nl:8443/voms/emutd/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.grid.sara.nl</name>
       <port>30010</port>
       <cert>voms.grid.sara.nl.pem</cert>
       <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
    </server>
  </vo>
 
  <vo>
    <name>esr</name>
    <admin>https://voms.grid.sara.nl:8443/voms/esr/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.grid.sara.nl</name>
       <port>30001</port>
       <cert>voms.grid.sara.nl.pem</cert>
       <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
    </server>
  </vo>
 
  <vo>
    <name>gaussian</name>
    <admin>https://voms.cyf-kr.edu.pl:8443/voms/gaussian/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.cyf-kr.edu.pl</name>
       <port>15001</port>
       <cert>voms.cyf-kr.edu.pl.pem</cert>
       <dn>/C=PL/O=GRID/O=Cyfronet/CN=voms.cyf-kr.edu.pl</dn>
    </server>
  </vo>
 
  <vo>
    <name>geant4</name>
    <admin>https://voms.cern.ch:8443/voms/geant4/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.cern.ch</name>
       <port>15007</port>
       <cert>voms.cern.ch.pem</cert>
       <dn>/DC=ch/DC=cern/OU=computers/CN=lcg-voms.cern.ch</dn>
    </server>
  </vo>
 
  <vo>
    <name>lhcb</name>
    <admin>https://lcg-voms.cern.ch:8443/voms/lhcb/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>lcg-voms.cern.ch</name>
       <port>15003</port>
       <cert>lcg-voms.cern.ch.pem</cert>
       <dn>/DC=ch/DC=cern/OU=computers/CN=lcg-voms.cern.ch</dn>
    </server>
  </vo>
 
  <vo>
    <name>lhcb</name>
    <admin>https://voms.cern.ch:8443/voms/lhcb/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.cern.ch</name>
       <port>15003</port>
       <cert>voms.cern.ch.pem</cert>
       <dn>/DC=ch/DC=cern/OU=computers/CN=voms.cern.ch</dn>
    </server>
  </vo>
 
  <vo>
    <name>lofar</name>
    <admin>https://voms.grid.sara.nl:8443/voms/lofar/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.grid.sara.nl</name>
       <port>30019</port>
       <cert>voms.grid.sara.nl.pem</cert>
       <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
    </server>
  </vo>
 
  <vo>
    <name>lsgrid</name>
    <admin>https://voms.grid.sara.nl:8443/voms/lsgrid/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.grid.sara.nl</name>
       <port>30018</port>
       <cert>voms.grid.sara.nl.pem</cert>
       <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
    </server>
  </vo>
 
  <vo>
    <name>ncf</name>
    <admin>https://voms.grid.sara.nl:8443/voms/ncf/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.grid.sara.nl</name>
       <port>30014</port>
       <cert>voms.grid.sara.nl.pem</cert>
       <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
    </server>
  </vo>
 
  <vo>
    <name>nlesc.nl</name>
    <admin>https://voms.grid.sara.nl:8443/voms/nlesc.nl/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.grid.sara.nl</name>
       <port>30025</port>
       <cert>voms.grid.sara.nl.pem</cert>
       <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
    </server>
  </vo>
 
  <vo>
    <name>omegac</name>
    <admin>https://voms.grid.sara.nl:8443/voms/omegac/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.grid.sara.nl</name>
       <port>30020</port>
       <cert>voms.grid.sara.nl.pem</cert>
       <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
    </server>
  </vo>
 
  <vo>
    <name>ops</name>
    <admin>https://lcg-voms.cern.ch:8443/voms/ops/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>lcg-voms.cern.ch</name>
       <port>15009</port>
       <cert>lcg-voms.cern.ch.pem</cert>
       <dn>/DC=ch/DC=cern/OU=computers/CN=lcg-voms.cern.ch</dn>
    </server>
  </vo>
 
  <vo>
    <name>ops</name>
    <admin>https://voms.cern.ch:8443/voms/ops/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.cern.ch</name>
       <port>15004</port>
       <cert>voms.cern.ch.pem</cert>
       <dn>/DC=ch/DC=cern/OU=computers/CN=voms.cern.ch</dn>
    </server>
  </vo>
 
  <vo>
    <name>pheno</name>
    <admin>https://voms.gridpp.ac.uk:8443/voms/pheno/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.gridpp.ac.uk</name>
       <port>15011</port>
       <cert>voms.gridpp.ac.uk.pem</cert>
       <dn>/C=UK/O=eScience/OU=Manchester/L=HEP/CN=voms.gridpp.ac.uk</dn>
    </server>
  </vo>
 
  <vo>
    <name>phicos</name>
    <admin>https://voms.grid.sara.nl:8443/voms/phicos/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.grid.sara.nl</name>
       <port>30009</port>
       <cert>voms.grid.sara.nl.pem</cert>
       <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
    </server>
  </vo>
 
  <vo>
    <name>pvier</name>
    <admin>https://voms.grid.sara.nl:8443/voms/pvier/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.grid.sara.nl</name>
       <port>30000</port>
       <cert>voms.grid.sara.nl.pem</cert>
       <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
    </server>
  </vo>
 
  <vo>
    <name>saradmins</name>
    <admin>https://voms.grid.sara.nl:8443/voms/saradmins/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.grid.sara.nl</name>
       <port>30023</port>
       <cert>voms.grid.sara.nl.pem</cert>
       <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
    </server>
  </vo>
 
  <vo>
    <name>scia</name>
    <admin>https://voms.grid.sara.nl:8443/voms/scia/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.grid.sara.nl</name>
       <port>30021</port>
       <cert>voms.grid.sara.nl.pem</cert>
       <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
    </server>
  </vo>
 
  <vo>
    <name>shiwa-workflow.eu</name>
    <admin>https://cclcgvomsli01.in2p3.fr:8443/voms/shiwa-workflow.eu/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>cclcgvomsli01.in2p3.fr</name>
       <port>15016</port>
       <cert>cclcgvomsli01.in2p3.fr.pem</cert>
       <dn>/O=GRID-FR/C=FR/O=CNRS/OU=CC-IN2P3/CN=cclcgvomsli01.in2p3.fr</dn>
    </server>
  </vo>
 
  <vo>
    <name>test_vo</name>
    <admin>https://voms.grid.sara.nl:8443/voms/test_vo/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.grid.sara.nl</name>
       <port>30017</port>
       <cert>voms.grid.sara.nl.pem</cert>
       <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
    </server>
  </vo>
 
  <vo>
    <name>tutor</name>
    <admin>https://voms.grid.sara.nl:8443/voms/tutor/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.grid.sara.nl</name>
       <port>30007</port>
       <cert>voms.grid.sara.nl.pem</cert>
       <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
    </server>
  </vo>
 
  <vo>
    <name>vldbi</name>
    <admin>https://voms.grid.sara.nl:8443/voms/vldbi/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.grid.sara.nl</name>
       <port>30006</port>
       <cert>voms.grid.sara.nl.pem</cert>
       <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
    </server>
  </vo>
 
  <vo>
    <name>vlefi</name>
    <admin>https://voms.grid.sara.nl:8443/voms/vlefi/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.grid.sara.nl</name>
       <port>30004</port>
       <cert>voms.grid.sara.nl.pem</cert>
       <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
    </server>
  </vo>
 
  <vo>
    <name>vlemed</name>
    <admin>https://voms.grid.sara.nl:8443/voms/vlemed/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.grid.sara.nl</name>
       <port>30003</port>
       <cert>voms.grid.sara.nl.pem</cert>
       <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
    </server>
  </vo>
 
  <vo>
    <name>vlibu</name>
    <admin>https://voms.grid.sara.nl:8443/voms/vlibu/webui/admin</admin> <!-- guessed... -->
    <server>
       <name>voms.grid.sara.nl</name>
       <port>30002</port>
       <cert>voms.grid.sara.nl.pem</cert>
       <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
    </server>
  </vo>
</voms>
<!-- END generated voms.xml  -->
